/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 1

enum ts_symbol_identifiers {
  sym_null = 1,
  sym_unit = 2,
  anon_sym_true = 3,
  anon_sym_false = 4,
  sym_int = 5,
  sym_int32 = 6,
  sym_int64 = 7,
  sym_float = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_LBRACK = 12,
  anon_sym_SEMI = 13,
  anon_sym_RBRACK = 14,
  anon_sym_LT = 15,
  anon_sym_GT = 16,
  anon_sym_COLON = 17,
  anon_sym_POUND = 18,
  sym_identifier = 19,
  sym_char = 20,
  sym_string = 21,
  sym_source_file = 22,
  sym__value = 23,
  sym_boolean = 24,
  sym_pair = 25,
  sym_list = 26,
  sym_record = 27,
  sym_field = 28,
  sym_constructor = 29,
  aux_sym_list_repeat1 = 30,
  aux_sym_record_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_null] = "null",
  [sym_unit] = "unit",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_int] = "int",
  [sym_int32] = "int32",
  [sym_int64] = "int64",
  [sym_float] = "float",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_SEMI] = ";",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_COLON] = ":",
  [anon_sym_POUND] = "#",
  [sym_identifier] = "identifier",
  [sym_char] = "char",
  [sym_string] = "string",
  [sym_source_file] = "source_file",
  [sym__value] = "_value",
  [sym_boolean] = "boolean",
  [sym_pair] = "pair",
  [sym_list] = "list",
  [sym_record] = "record",
  [sym_field] = "field",
  [sym_constructor] = "constructor",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_record_repeat1] = "record_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_null] = sym_null,
  [sym_unit] = sym_unit,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_int] = sym_int,
  [sym_int32] = sym_int32,
  [sym_int64] = sym_int64,
  [sym_float] = sym_float,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_identifier] = sym_identifier,
  [sym_char] = sym_char,
  [sym_string] = sym_string,
  [sym_source_file] = sym_source_file,
  [sym__value] = sym__value,
  [sym_boolean] = sym_boolean,
  [sym_pair] = sym_pair,
  [sym_list] = sym_list,
  [sym_record] = sym_record,
  [sym_field] = sym_field,
  [sym_constructor] = sym_constructor,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_int] = {
    .visible = true,
    .named = true,
  },
  [sym_int32] = {
    .visible = true,
    .named = true,
  },
  [sym_int64] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_char] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
};

static const TSSymbol ts_supertype_symbols[SUPERTYPE_COUNT] = {
  sym__value,
};

static const TSMapSlice ts_supertype_map_slices[] = {
  [sym__value] = {.index = 0, .length = 13},
};

static const TSSymbol ts_supertype_map_entries[] = {
  [0] =
    sym_boolean,
    sym_char,
    sym_constructor,
    sym_float,
    sym_int,
    sym_int32,
    sym_int64,
    sym_list,
    sym_null,
    sym_pair,
    sym_record,
    sym_string,
    sym_unit,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '"', 2,
        '#', 40,
        '\'', 18,
        '(', 31,
        ')', 33,
        ',', 32,
        '-', 15,
        ':', 39,
        ';', 35,
        '<', 37,
        '>', 38,
        '[', 34,
        ']', 36,
        'f', 41,
        'n', 50,
        't', 47,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '#', 40,
        '\'', 18,
        '(', 31,
        '-', 15,
        '<', 37,
        '[', 34,
        ']', 36,
        'f', 5,
        'n', 14,
        't', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(17);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(52);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(7);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 14:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 18:
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(3);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_unit);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_int);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == 'L') ADVANCE(29);
      if (lookahead == 'l') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_int32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_int64);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(22);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_char);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 4},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [sym_unit] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_int] = ACTIONS(1),
    [sym_int32] = ACTIONS(1),
    [sym_int64] = ACTIONS(1),
    [sym_float] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_char] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym__value] = STATE(32),
    [sym_boolean] = STATE(12),
    [sym_pair] = STATE(12),
    [sym_list] = STATE(12),
    [sym_record] = STATE(12),
    [sym_constructor] = STATE(12),
    [sym_null] = ACTIONS(3),
    [sym_unit] = ACTIONS(3),
    [anon_sym_true] = ACTIONS(5),
    [anon_sym_false] = ACTIONS(5),
    [sym_int] = ACTIONS(7),
    [sym_int32] = ACTIONS(3),
    [sym_int64] = ACTIONS(3),
    [sym_float] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_char] = ACTIONS(3),
    [sym_string] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__value] = STATE(19),
    [sym_boolean] = STATE(12),
    [sym_pair] = STATE(12),
    [sym_list] = STATE(12),
    [sym_record] = STATE(12),
    [sym_constructor] = STATE(12),
    [sym_null] = ACTIONS(3),
    [sym_unit] = ACTIONS(3),
    [anon_sym_true] = ACTIONS(5),
    [anon_sym_false] = ACTIONS(5),
    [sym_int] = ACTIONS(7),
    [sym_int32] = ACTIONS(3),
    [sym_int64] = ACTIONS(3),
    [sym_float] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_RBRACK] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_char] = ACTIONS(3),
    [sym_string] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__value] = STATE(30),
    [sym_boolean] = STATE(12),
    [sym_pair] = STATE(12),
    [sym_list] = STATE(12),
    [sym_record] = STATE(12),
    [sym_constructor] = STATE(12),
    [sym_null] = ACTIONS(3),
    [sym_unit] = ACTIONS(3),
    [anon_sym_true] = ACTIONS(5),
    [anon_sym_false] = ACTIONS(5),
    [sym_int] = ACTIONS(7),
    [sym_int32] = ACTIONS(3),
    [sym_int64] = ACTIONS(3),
    [sym_float] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_char] = ACTIONS(3),
    [sym_string] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym__value] = STATE(35),
    [sym_boolean] = STATE(12),
    [sym_pair] = STATE(12),
    [sym_list] = STATE(12),
    [sym_record] = STATE(12),
    [sym_constructor] = STATE(12),
    [sym_null] = ACTIONS(3),
    [sym_unit] = ACTIONS(3),
    [anon_sym_true] = ACTIONS(5),
    [anon_sym_false] = ACTIONS(5),
    [sym_int] = ACTIONS(7),
    [sym_int32] = ACTIONS(3),
    [sym_int64] = ACTIONS(3),
    [sym_float] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_char] = ACTIONS(3),
    [sym_string] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym__value] = STATE(28),
    [sym_boolean] = STATE(12),
    [sym_pair] = STATE(12),
    [sym_list] = STATE(12),
    [sym_record] = STATE(12),
    [sym_constructor] = STATE(12),
    [sym_null] = ACTIONS(3),
    [sym_unit] = ACTIONS(3),
    [anon_sym_true] = ACTIONS(5),
    [anon_sym_false] = ACTIONS(5),
    [sym_int] = ACTIONS(7),
    [sym_int32] = ACTIONS(3),
    [sym_int64] = ACTIONS(3),
    [sym_float] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_char] = ACTIONS(3),
    [sym_string] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym__value] = STATE(26),
    [sym_boolean] = STATE(12),
    [sym_pair] = STATE(12),
    [sym_list] = STATE(12),
    [sym_record] = STATE(12),
    [sym_constructor] = STATE(12),
    [sym_null] = ACTIONS(3),
    [sym_unit] = ACTIONS(3),
    [anon_sym_true] = ACTIONS(5),
    [anon_sym_false] = ACTIONS(5),
    [sym_int] = ACTIONS(7),
    [sym_int32] = ACTIONS(3),
    [sym_int64] = ACTIONS(3),
    [sym_float] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_char] = ACTIONS(3),
    [sym_string] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym__value] = STATE(36),
    [sym_boolean] = STATE(12),
    [sym_pair] = STATE(12),
    [sym_list] = STATE(12),
    [sym_record] = STATE(12),
    [sym_constructor] = STATE(12),
    [sym_null] = ACTIONS(3),
    [sym_unit] = ACTIONS(3),
    [anon_sym_true] = ACTIONS(5),
    [anon_sym_false] = ACTIONS(5),
    [sym_int] = ACTIONS(7),
    [sym_int32] = ACTIONS(3),
    [sym_int64] = ACTIONS(3),
    [sym_float] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(15),
    [sym_char] = ACTIONS(3),
    [sym_string] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(19), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [9] = 1,
    ACTIONS(21), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [18] = 1,
    ACTIONS(23), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [27] = 1,
    ACTIONS(25), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [36] = 1,
    ACTIONS(27), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [45] = 1,
    ACTIONS(29), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [54] = 1,
    ACTIONS(31), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [63] = 1,
    ACTIONS(33), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [72] = 1,
    ACTIONS(35), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [81] = 1,
    ACTIONS(37), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_RBRACK,
      anon_sym_GT,
  [90] = 3,
    ACTIONS(39), 1,
      anon_sym_SEMI,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      aux_sym_list_repeat1,
  [100] = 3,
    ACTIONS(39), 1,
      anon_sym_SEMI,
    ACTIONS(43), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      aux_sym_list_repeat1,
  [110] = 3,
    ACTIONS(45), 1,
      anon_sym_GT,
    ACTIONS(47), 1,
      sym_identifier,
    STATE(21), 1,
      sym_field,
  [120] = 3,
    ACTIONS(49), 1,
      anon_sym_SEMI,
    ACTIONS(51), 1,
      anon_sym_GT,
    STATE(22), 1,
      aux_sym_record_repeat1,
  [130] = 3,
    ACTIONS(49), 1,
      anon_sym_SEMI,
    ACTIONS(53), 1,
      anon_sym_GT,
    STATE(23), 1,
      aux_sym_record_repeat1,
  [140] = 3,
    ACTIONS(55), 1,
      anon_sym_SEMI,
    ACTIONS(58), 1,
      anon_sym_GT,
    STATE(23), 1,
      aux_sym_record_repeat1,
  [150] = 3,
    ACTIONS(60), 1,
      anon_sym_SEMI,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      aux_sym_list_repeat1,
  [160] = 2,
    ACTIONS(47), 1,
      sym_identifier,
    STATE(27), 1,
      sym_field,
  [167] = 1,
    ACTIONS(65), 2,
      anon_sym_SEMI,
      anon_sym_GT,
  [172] = 1,
    ACTIONS(58), 2,
      anon_sym_SEMI,
      anon_sym_GT,
  [177] = 1,
    ACTIONS(63), 2,
      anon_sym_SEMI,
      anon_sym_RBRACK,
  [182] = 1,
    ACTIONS(67), 1,
      anon_sym_LPAREN,
  [186] = 1,
    ACTIONS(69), 1,
      anon_sym_COMMA,
  [190] = 1,
    ACTIONS(71), 1,
      anon_sym_COLON,
  [194] = 1,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
  [198] = 1,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
  [202] = 1,
    ACTIONS(77), 1,
      sym_identifier,
  [206] = 1,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
  [210] = 1,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 9,
  [SMALL_STATE(10)] = 18,
  [SMALL_STATE(11)] = 27,
  [SMALL_STATE(12)] = 36,
  [SMALL_STATE(13)] = 45,
  [SMALL_STATE(14)] = 54,
  [SMALL_STATE(15)] = 63,
  [SMALL_STATE(16)] = 72,
  [SMALL_STATE(17)] = 81,
  [SMALL_STATE(18)] = 90,
  [SMALL_STATE(19)] = 100,
  [SMALL_STATE(20)] = 110,
  [SMALL_STATE(21)] = 120,
  [SMALL_STATE(22)] = 130,
  [SMALL_STATE(23)] = 140,
  [SMALL_STATE(24)] = 150,
  [SMALL_STATE(25)] = 160,
  [SMALL_STATE(26)] = 167,
  [SMALL_STATE(27)] = 172,
  [SMALL_STATE(28)] = 177,
  [SMALL_STATE(29)] = 182,
  [SMALL_STATE(30)] = 186,
  [SMALL_STATE(31)] = 190,
  [SMALL_STATE(32)] = 194,
  [SMALL_STATE(33)] = 198,
  [SMALL_STATE(34)] = 202,
  [SMALL_STATE(35)] = 206,
  [SMALL_STATE(36)] = 210,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__value, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 3, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 4, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair, 5, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constructor, 5, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 3, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_rensai(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .supertype_map_slices = ts_supertype_map_slices,
    .supertype_map_entries = ts_supertype_map_entries,
    .supertype_symbols = ts_supertype_symbols,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "rensai",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
